
      tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "surface": "#071325",
              "on-secondary": "#552100",
              "on-secondary-container": "#4a1c00",
              "error-container": "#93000a",
              "primary-container": "#00a3ff",
              "secondary-container": "#ec6a06",
              "surface-container": "#142032",
              "surface-tint": "#98cbff",
              "tertiary": "#d2bbff",
              "on-tertiary-container": "#430096",
              "on-error-container": "#ffdad6",
              "background": "#071325",
              "surface-dim": "#071325",
              "on-primary-fixed-variant": "#004a77",
              "on-primary-fixed": "#001d33",
              "on-primary": "#003354",
              "tertiary-fixed-dim": "#d2bbff",
              "surface-container-lowest": "#030e20",
              "on-tertiary-fixed": "#25005a",
              "tertiary-fixed": "#eaddff",
              "surface-container-low": "#101c2e",
              "primary-fixed": "#cfe5ff",
              "on-secondary-fixed-variant": "#783200",
              "secondary-fixed": "#ffdbca",
              "outline-variant": "#3f4852",
              "error": "#ffb4ab",
              "secondary": "#ffb690",
              "primary": "#00A3FF",
              "surface-container-highest": "#2a3548",
              "on-surface-variant": "#bec7d4",
              "on-tertiary-fixed-variant": "#5a00c6",
              "on-error": "#690005",
              "on-background": "#d7e3fc",
              "surface-container-high": "#1f2a3d",
              "on-surface": "#d7e3fc",
              "primary-fixed-dim": "#98cbff",
              "on-secondary-fixed": "#341100",
              "surface-bright": "#2e394d",
              "tertiary-container": "#ae86ff",
              "inverse-on-surface": "#253144",
              "inverse-primary": "#00629d",
              "on-primary-container": "#00375a",
              "inverse-surface": "#d7e3fc",
              "outline": "#88919d",
              "on-tertiary": "#3f008e",
              "secondary-fixed-dim": "#ffb690",
              "surface-variant": "#2a3548"
            },
            fontFamily: {
              "headline": ["Inter", "sans-serif"],
              "body": ["Inter", "sans-serif"],
              "label": ["Inter", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
          },
        },
      }
    